ALTER TABLE sites ADD COLUMN IF NOT EXISTS crawl_enabled boolean NOT NULL DEFAULT true;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS max_pages integer NOT NULL DEFAULT 500;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS crawl_delay_ms integer NOT NULL DEFAULT 300;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS request_timeout_ms integer NOT NULL DEFAULT 10000;
DO $$ BEGIN ALTER TABLE sites ADD CONSTRAINT sites_max_pages_check CHECK (max_pages BETWEEN 1 AND 5000); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS cancellation_requested_at timestamptz;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_discovered integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_requested integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_succeeded integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_failed integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_indexable integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS pages_non_indexable integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS issues_found integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS duration_ms integer;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS failure_code text;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS failure_summary text;
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS robots_meta jsonb NOT NULL DEFAULT '{}';
ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS summary jsonb NOT NULL DEFAULT '{}';
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS final_url text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS redirect_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS response_bytes integer;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS response_time_ms integer;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS title_length integer;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS description_length integer;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS h1_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS primary_h1 text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS h2_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS canonical_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS robots_meta text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS x_robots_tag text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS indexable boolean NOT NULL DEFAULT false;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS indexability_reasons jsonb NOT NULL DEFAULT '[]';
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS word_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS internal_links_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS external_links_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS nofollow_internal_count integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS content_hash text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS crawl_depth integer NOT NULL DEFAULT 0;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS discovery_source text NOT NULL DEFAULT 'LINK';
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS in_sitemap boolean NOT NULL DEFAULT false;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS language text;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS viewport_present boolean NOT NULL DEFAULT false;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS fetched_at timestamptz;
ALTER TABLE crawl_pages ADD COLUMN IF NOT EXISTS fetch_error_code text;
ALTER TABLE seo_issues ADD COLUMN IF NOT EXISTS crawl_run_id uuid REFERENCES crawl_runs(id) ON DELETE CASCADE;
ALTER TABLE seo_issues ADD COLUMN IF NOT EXISTS url text NOT NULL DEFAULT '';
ALTER TABLE seo_issues ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'TECHNICAL';
ALTER TABLE seo_issues ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'OPEN';
ALTER TABLE seo_issues ADD COLUMN IF NOT EXISTS detected_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS crawl_runs_site_status_idx ON crawl_runs(site_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS crawl_pages_run_status_idx ON crawl_pages(crawl_run_id,status_code);
CREATE INDEX IF NOT EXISTS crawl_pages_run_indexable_idx ON crawl_pages(crawl_run_id,indexable);
CREATE INDEX IF NOT EXISTS crawl_pages_content_hash_idx ON crawl_pages(crawl_run_id,content_hash);
CREATE INDEX IF NOT EXISTS seo_issues_run_severity_idx ON seo_issues(crawl_run_id,severity);
CREATE INDEX IF NOT EXISTS seo_issues_run_code_idx ON seo_issues(crawl_run_id,rule_code);
