ALTER TABLE serp_api_captures
  ADD COLUMN IF NOT EXISTS review_policy text NOT NULL
  DEFAULT 'AUTO_ACCEPT_IF_POLICY_ALLOWS'
  CHECK (review_policy IN ('AUTO_ACCEPT_IF_POLICY_ALLOWS','OWNER_REVIEW_REQUIRED'));
